# Generated by Django 4.1.5 on 2023-01-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Директор'), (2, 'Администратор'), (3, 'Мерчендайзер'), (4, 'Аналитик')], verbose_name='Должность'),
        ),
    ]
