# Generated by Django 4.1.5 on 2023-01-18 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house_number', models.PositiveSmallIntegerField(verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='network.address', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Имя')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
                ('launch_date', models.DateField(verbose_name='Дата выхода на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Имя')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Завод'), (2, 'Дистрибьютор'), (3, 'Дилерский центр'), (4, 'Крупная розничная сеть'), (5, 'Индивидуальный предприниматель')], default=1, verbose_name='Уровень')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Задолженность перед поставщиком')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='network.contact', verbose_name='Контакты')),
                ('products', models.ManyToManyField(related_name='organizations', to='network.product', verbose_name='Продукты')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='network.organization', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
