# Generated by Django 4.1.5 on 2023-01-18 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='staff',
        ),
        migrations.AddField(
            model_name='organization',
            name='staff',
            field=models.ManyToManyField(related_name='organization', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
