# Generated by Django 4.1.5 on 2023-01-19 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0003_alter_organization_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='debt_to_supplier',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Задолженность (руб.)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='network.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='organization', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
    ]
