# Generated by Django 4.1.5 on 2023-01-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_organization_debt_to_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Завод'), (2, 'Дистрибьютор'), (3, 'Дилерский центр'), (4, 'Крупная розничная сеть'), (5, 'Индивидуальный предприниматель')], verbose_name='Уровень'),
        ),
    ]
